/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {
  interface AppHome {}
  interface AppProfile {
    'match': MatchResults;
  }
  interface EmbeddedComponent {
    'text': string;
  }
  interface ParentComponent {}
  interface SampleComponent {
    'getState': () => Promise<boolean>;
    'name': string;
    'state': boolean;
    'text': string;
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLEmbeddedComponentElement extends Components.EmbeddedComponent, HTMLStencilElement {}
  var HTMLEmbeddedComponentElement: {
    prototype: HTMLEmbeddedComponentElement;
    new (): HTMLEmbeddedComponentElement;
  };

  interface HTMLParentComponentElement extends Components.ParentComponent, HTMLStencilElement {}
  var HTMLParentComponentElement: {
    prototype: HTMLParentComponentElement;
    new (): HTMLParentComponentElement;
  };

  interface HTMLSampleComponentElement extends Components.SampleComponent, HTMLStencilElement {}
  var HTMLSampleComponentElement: {
    prototype: HTMLSampleComponentElement;
    new (): HTMLSampleComponentElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'embedded-component': HTMLEmbeddedComponentElement;
    'parent-component': HTMLParentComponentElement;
    'sample-component': HTMLSampleComponentElement;
  }
}

declare namespace LocalJSX {
  interface AppHome extends JSXBase.HTMLAttributes<HTMLAppHomeElement> {}
  interface AppProfile extends JSXBase.HTMLAttributes<HTMLAppProfileElement> {
    'match'?: MatchResults;
  }
  interface EmbeddedComponent extends JSXBase.HTMLAttributes<HTMLEmbeddedComponentElement> {
    'text'?: string;
  }
  interface ParentComponent extends JSXBase.HTMLAttributes<HTMLParentComponentElement> {}
  interface SampleComponent extends JSXBase.HTMLAttributes<HTMLSampleComponentElement> {
    'name'?: string;
    'onActive'?: (event: CustomEvent<any>) => void;
    'state'?: boolean;
    'text'?: string;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-profile': AppProfile;
    'embedded-component': EmbeddedComponent;
    'parent-component': ParentComponent;
    'sample-component': SampleComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


